--
-- Brickshare Seed File
-- Este archivo está intencionalmente vacío.
-- Los datos de prueba se insertan mediante:
-- 1. Migraciones (brickshare_pudo_locations, inventory_sets triggers)
-- 2. Scripts manuales (scripts/create-user-brickshare.sql, etc.)
--
-- Para agregar datos de prueba, usa scripts SQL dedicados en /scripts/
--

-- Seed vacío - las migraciones ya insertan los datos necesarios
