version: 2
updates:
  # Check for npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "EnriquePerez00"
    allow:
      - dependency-type: "all"
    ignore:
      # Add packages to ignore if needed
      - dependency-name: "typescript"
        versions: ["5.4", "5.5"]

  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "EnriquePerez00"