#!/bin/bash

# ═══════════════════════════════════════════════════════════════
# Setup E2E Test Environment
# ═══════════════════════════════════════════════════════════════
# This script helps configure the environment variables needed
# for E2E tests to run properly.
# ═══════════════════════════════════════════════════════════════

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "🔧 Setting up E2E Test Environment..."
echo ""

# Check if Supabase is running
if ! command -v supabase &> /dev/null; then
    echo -e "${RED}❌ Supabase CLI not found${NC}"
    echo "Please install it: brew install supabase/tap/supabase"
    exit 1
fi

# Check Supabase status
if ! supabase status &> /dev/null; then
    echo -e "${YELLOW}⚠️  Supabase is not running${NC}"
    echo "Starting Supabase..."
    cd ../.. && supabase start
    cd apps/web
else
    echo -e "${GREEN}✅ Supabase is running${NC}"
fi

# Get Supabase credentials
SUPABASE_URL=$(supabase status | grep "API URL" | awk '{print $3}')
SUPABASE_ANON_KEY=$(supabase status | grep "anon key" | awk '{print $3}')
SUPABASE_SERVICE_ROLE_KEY=$(supabase status | grep "service_role key" | awk '{print $3}')

# Create or update .env.local
ENV_FILE=".env.local"

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  .env.local already exists, backing up...${NC}"
    cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
fi

cat > "$ENV_FILE" << EOF
# ═══════════════════════════════════════════════════════════════
# Local Development Environment Variables
# ═══════════════════════════════════════════════════════════════
# Auto-generated by e2e/setup-e2e-env.sh on $(date)
# ═══════════════════════════════════════════════════════════════

# Supabase Configuration
VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

# App Configuration
VITE_APP_URL=http://localhost:5173

# Stripe Configuration (Test Mode)
VITE_STRIPE_PUBLISHABLE_KEY=pk_test_your_key_here

# Feature Flags
VITE_ENABLE_ANALYTICS=false
VITE_ENABLE_DEBUG=true
EOF

echo -e "${GREEN}✅ Created .env.local with Supabase credentials${NC}"
echo ""
echo "📋 Environment variables configured:"
echo "   VITE_SUPABASE_URL: $SUPABASE_URL"
echo "   VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:0:20}..."
echo "   SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:0:20}..."
echo ""
echo -e "${GREEN}🎉 E2E environment setup complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Update VITE_STRIPE_PUBLISHABLE_KEY in .env.local with your test key"
echo "2. Run E2E tests: npx playwright test"
echo "3. View test report: npx playwright show-report"